version: '3'
services:
  proxy:
    build: ./proxy
    volumes:
      - ./proxy:/proxy
    ports: 
      - 1506:80
    depends_on:
      - app1
      - app2
      
  app1:
    image: mathcovax/ehpadjs
    volumes:
      - ./app1:/app
    environment:
      EHPADJS_NODEMON: "true"
      # EHPADJS_NPM_INSTALL: "true"
      # EHPADJS_PORT="80"
      # EHPADJS_COMMAND="node -v"
    depends_on:
      - mongo

  app2:
    image: mathcovax/ehpadjs
    volumes:
      - ./app2:/app
    environment:
      EHPADJS_NODEMON: "true"
      # EHPADJS_NPM_INSTALL: "true"
      # EHPADJS_PORT="80"
      # EHPADJS_COMMAND="node -v"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/opt/mongodb/db

volumes:
  mongo_data: {}