version: '3'
services:
  nginx1:
    container_name: nginx1
    build:
      context: ./.docker/nginx/
      args:
        - CONF_FILE=default1.conf
    ports:
      - 81:80
    volumes:
      - ./php1:/var/www/html
    depends_on:
      - laravel1
  
  laravel1:
    container_name: laravel1
    build:
      context: ./.docker/laravel/
    volumes:
      - ./laravel1:/var/www/html

  # nginx2:
  #   container_name: nginx2
  #   build:
  #     context: ./.docker/nginx/
  #     args:
  #       - CONF_FILE=default2.conf
  #   ports:
  #     - 82:80
  #   volumes:
  #     - ./php2:/var/www/html
  #   depends_on:
  #     - php2

  # php1:
  #   container_name: php1
  #   build: ./.docker/php/
  #   volumes:
  #     - ./php1:/var/www/html
    
  # php2:
  #   container_name: php2
  #   build: ./.docker/php/
  #   volumes:
  #     - ./php2:/var/www/html
      
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp
      MYSQL_USER: user
      MYSQL_PASSWORD: user

volumes:
  db_data: {}